#PBS -lwalltime=24:00:00
#PBS -lselect=1:ncpus=5:mem=30gb

cd $HOME/Transfer_Learning_Gaussian_Processes
module load anaconda3/personal
source activate tlgps

for SEED in {1..3}
    do for DATASEED in {1..5}
        do for RELATIONTYPE in {1..3}
            do
                qsub -v SEED=$SEED, DATASEED=$DATASEED, RELATIONTYPE=$RELATIONTYPE model_learning_curves/subset_runs.pbs
            done
        done
    done